# Generated by Django 5.2.3 on 2025-07-01 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_profile_picture'),
        ('users', '0012_customuser_country_code_customuser_gender'),
    ]

    operations = [
    ]
