# Generated by Django 5.2.3 on 2025-07-03 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_merge_20250701_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='login',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='logout',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='salary_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('leave', 'Leave'), ('wfh', 'Work From Home'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_employee_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
